language: go

branches:
  only:
    - master

cache:
  directories:
    - $GOPATH/src
    - $GOPATH/pkg

install:
  - go get -u github.com/onsi/ginkgo/ginkgo  # installs the ginkgo CLI
  - go get -u github.com/onsi/gomega/...     # fetches the matcher library
  - go get -v -t ./...
  - go install github.com/onsi/ginkgo/ginkgo

go:
  - 1.8
  - 1.9

script:
  - go test

notifications:
  slack:
    secure: TxQ+63HarzznltmpqbfYG38AsQ/SyRqkt7LKE19mO2Xex7w7s6XVcpu9kvzcT8JF0HtSeCvQNx5qiAFyzyswuZrQ6Ue/DBrLxgy2hYTE+XU4bTaIEGHOhOLGcWMBtTSDVmMF3I+0vj7GWa4iobLVP+asrSQmvRCOVXbZivo65gu+DfycrMC3MKMj704Akgz9JcvjE/p/akkpGeaCmyRm46MQsN1aeCMfgP91s/XtGZvakdrvwyTVZ+5K8iyOwnCJhh3hJCNnhkDYgh47lBwR12pN2MvvBAXpW4Vw9+LoBjkWWlhq4scH6N8Da5GdM9MWdfpCfWPUefPHHYTs/3z9s9M6iPwi1A7xYWzfMLtLmMCenmTxXWqpr9YB+9C2lqz/TLgXmJUAmwAcvU8KybNGc8NDq9Itft6fYdOFsjLL/6QygR7VxCNe8BRu3ex7fUJeHTd6CEi8gKA/CyTxmgn3P7X9WzKO5vgBzKDgWXGsYYg+jPYaI9aoVyUendSeTeV6BFdcNjZGH0BGCguXpnDHHSlQpnSrRiG1mJ8j5xX6Z9KekDutrTM4f2YQ371FWa5hxVYQht4w+hM2kV0nqdY9GWU5zDmG1a4MTPVxrWl2MkL/jwebneJs517JJvgQthW4WYZ1+XLphdYIs+bFq9fjYEjceF2i5LdG/+An2NnYdkA=
